feat: add tirg multimodal encoder
jina-ai/jina-hub pull request #1136
Opened 2020-11-24 05:55 UTC by bhavsarpratik

2020-11-24 06:05 UTC, bhavsarpratik commented
@bwanglzu @JoanFM What is the error here
ConstructorError(None, None, "could not determine a constructor for the tag '!TirgMultiModalEncoder'", <_ruamel_yaml.Mark object at 0x7f847c3fcbf0>)

2020-11-24 06:45 UTC, JoanFM commented
> @bwanglzu @JoanFM What is the error here
> ConstructorError(None, None, "could not determine a constructor for the tag '!TirgMultiModalEncoder'", <_ruamel_yaml.Mark object at 0x7f847c3fcbf0>)

It failed when constructing the Executor from `yaml`

2020-11-24 06:48 UTC, JoanFM requested changes

2020-11-24 06:48 UTC, JoanFM commented on encoders/multimodal/TirgMultimodalEncoder/__init__.py
> +sys.path.append(".")
When moving here I think we can avoid using these `sys` tricks

2020-11-24 06:48 UTC, JoanFM commented on encoders/multimodal/TirgMultimodalEncoder/img_text_composition_models.py
> +# from jina.hub.encoders.image.TirgEncoder import text_model
remove these comments

2020-11-24 06:48 UTC, JoanFM commented on encoders/multimodal/TirgMultimodalEncoder/__init__.py
> +from img_text_composition_models import TIRG
Hide these `imports` inside functions so that it will avoid importing everything inside that file

2020-11-24 14:26 UTC, bwanglzu submitted a review, later dismissed
LGTM!

2020-12-17 06:33 UTC, JoanFM commented
Have u reprpoduced the same issue locally?

2020-12-17 10:08 UTC, bwanglzu commented
wired, CI failed

2020-12-21 08:51 UTC, JoanFM approved these changes

2020-12-21 08:51 UTC, merged