Migrate fast ica encoder
jina-ai/jina-hub pull request #139
Opened 2020-08-21 05:55 UTC by YueLiu-jina

There's still one fail at `test_save_and_load_config` in `TestClassFastICATrain`. Will continue on this later.

2020-08-21 06:02 UTC, JoanFM requested changes

2020-08-21 06:02 UTC, JoanFM commented on encoders/numeric/FastICAEncoder/README.md
> +note:
that is wrong under current level, that was before, now u can pass a pickled file from which to do encoding

2020-08-21 06:02 UTC, JoanFM commented on encoders/numeric/FastICAEncoder/tests/test_fasticaencoder.py
> +from encoders.numeric.test import TestClassNumeric
we do not want to have these kind of dependencies, every test needs to be self contained, so every test will have to implement its tests (test_encode, test_load ....)

2020-08-21 06:02 UTC, JoanFM commented on encoders/numeric/test.py
> +import os
This needs to be removed, every executor needs have its own self contained tests and no dependency from other files in the tree

2020-08-21 06:02 UTC, JoanFM commented
This is a missconception on how we have to tests executors (see comments also added in #136)

2020-08-24 09:28 UTC, nan-wang commented
@YueLiu-jina I'm looking into this PR

2020-08-24 10:02 UTC, hanxiao approved these changes

2020-08-24 10:06 UTC, hanxiao approved these changes

2020-08-24 10:06 UTC, merged

2020-08-25 01:20 UTC, JamesTang-jinaai commented on encoders/numeric/FastICAEncoder/requirements.txt
> +sklearn
should be `scikit-learn`