Migrate farm text encoder 152
jina-ai/jina-hub pull request #168
Opened 2020-08-25 05:32 UTC by YueLiu-jina

resolve #152 
waiting for using mock

2020-08-25 05:51 UTC, nan-wang requested changes

2020-08-25 05:51 UTC, nan-wang commented on encoders/nlp/FarmTextEncoder/tests/test_farmtextencoder.py
> +    print(encoder.__dict__)
```suggestion
```

2020-08-25 05:51 UTC, nan-wang commented on encoders/nlp/FarmTextEncoder/tests/test_farmtextencoder.py
> +# @pytest.mark.skipif('JINA_TEST_PRETRAINED' not in os.environ, reason='skip the pretrained test if not set')
```suggestion
class MockInference():
    def load(*args, **kwargs):
        return self
        
    def extract_vectors(dicts, *args, **kwargs):
        return [{'vec': np.random.random(target_output_dim)}]
       

@mock.patch('farm.infer.Inferencer', return_value=MockInference())
```

2020-08-25 05:51 UTC, nan-wang commented on encoders/nlp/FarmTextEncoder/tests/test_farmtextencoder.py
> +    rm_files([mlflow_dir])
check the PR at https://github.com/jina-ai/jina-hub/pull/169/files

2020-08-25 06:41 UTC, JoanFM commented on encoders/nlp/FarmTextEncoder/Dockerfile
> +FROM jinaai/jina
remember to use `:devel`

2020-08-25 06:41 UTC, JoanFM commented on encoders/nlp/FarmTextEncoder/tests/test_farmtextencoder.py
> +# @pytest.mark.skipif('JINA_TEST_PRETRAINED' not in os.environ, reason='skip the pretrained test if not set')
completely remove these lines

2020-08-25 15:20 UTC, hanxiao requested changes
need to add one unit test with real model not with mocked model, see our Slack discussion

2020-08-26 03:02 UTC, YueLiu-jina commented
added non-local test for test_encoding_result

2020-08-26 04:05 UTC, nan-wang requested changes

2020-08-26 04:05 UTC, nan-wang commented on encoders/nlp/FarmTextEncoder/Dockerfile
> +RUN pip install pytest pytest-mock mock && pytest
```suggestion
RUN pip install pytest pytest-mock mock && JINA_TEST_PRETRAINED='true' pytest
```

2020-08-26 07:09 UTC, nan-wang approved these changes
LGTM👍

2020-08-26 07:09 UTC, merged