Migrate universal sentence encoder
jina-ai/jina-hub pull request #171
Opened 2020-08-25 07:55 UTC by YueLiu-jina

2020-08-25 11:12 UTC, JoanFM commented on encoders/nlp/UniversalSentenceEncoder/tests/test_universalsentenceencoder.py
> +@mock.patch('tensorflow_hub.load', return_value=MockModule())
we can also add real case tests now

2020-08-25 15:23 UTC, hanxiao requested changes
need to add at least one non-mocked unit test for real-model test, see our discussion on the Slack

2020-08-26 02:29 UTC, YueLiu-jina commented on encoders/nlp/UniversalSentenceEncoder/tests/test_universalsentenceencoder.py
> +@mock.patch('tensorflow_hub.load', return_value=MockModule())
solved

2020-08-26 02:46 UTC, YueLiu-jina commented
added non-local test for test_encoding_result, all test pass

2020-08-26 05:53 UTC, nan-wang approved these changes
LGTM👍

2020-08-26 05:54 UTC, merged