feat(crafters): add AlbumentationsCrafter
jina-ai/jina-hub pull request #2480
Opened 2021-01-18 00:12 UTC by tadejsv

This adds AlbumentationsCrafter. Still WIP, tests not added yet.

2021-01-18 23:47 UTC, tadejsv commented
@JoanFM this is ready for review, although I will improve the readme tomorrow. Also, build fails due to some Jina problem, as all tests pass.

2021-01-19 06:05 UTC, JoanFM reviewed
The problem is that we need some default value for the input arguments, because we do some testing to see if the image can be loaded in a Flow and in this case it will raise an Exception.

2021-01-19 06:07 UTC, JoanFM requested changes

2021-01-19 06:07 UTC, JoanFM commented on crafters/image/AlbumentationsCrafter/requirements.txt
> +jina
please remove jina as the image is based om jina

2021-01-19 14:51 UTC, tadejsv commented
@JoanFM any idea why the build is failing now? I've addressed the previous issues. Also, this PR is now complete

2021-01-19 15:00 UTC, JoanFM submitted a review, later dismissed

2021-01-20 07:01 UTC, JoanFM commented on crafters/image/AlbumentationsCrafter/manifest.yml
> +author: Jina AI Dev-Team (dev-team@jina.ai)
Hey @tadejsv , is not the root of the problem, so no big deal, but you are welcome to attribute yourself as the author of this Hub Executor

2021-01-20 07:14 UTC, JoanFM commented
Hey @tadejsv , I have tried locally, and it seems to be your `Dockerfile` that is not being properly built from `jina-hub`. I would suggest to move it to the old way, and open an issue in `jina-core` to have it solved

2021-01-20 07:15 UTC, tadejsv commented
@JoanFM also (probably) not the root of the problem, but when exploring the URL of the docker request, it seems that jina inserts labels after every `FROM` line in the dockerfile. The correct way would be to do it only after the last `FROM`

Here's the decoded URL:
```
docker://localhost/v1.40/build?t=jinahub/pod.crafter.albumentationscrafter:0.0.1-0.9.18&q=False&nocache=False&rm=True&forcerm=False&pull=True&dockerfile=.dockerfile.85ba69d05f9914e2aef3438da3fd8b99512ce32e&dockerfile=FROM jinaai/jina AS base
LABEL ai.jina.hub.name="AlbumentationsCrafter" \      
ai.jina.hub.description="Apply transformations from the Albumentations package to the image." \      
ai.jina.hub.type="pod" \      
ai.jina.hub.author="Tadej Svetina (@tadejsv)" \      
ai.jina.hub.url="https://jina.ai" \      
ai.jina.hub.documentation="https://github.com/jina-ai/jina-hub" \      
ai.jina.hub.version="0.0.1" \      
ai.jina.hub.vendor="Jina AI Limited" \      
ai.jina.hub.license="apache-2.0" \      
ai.jina.hub.avatar="None" \      
ai.jina.hub.platform="['linux/amd64']" \      
ai.jina.hub.keywords="['image', 'transform', 'augmentation', 'albumentations']" \      
ai.jina.hub.manifest_version="1" \      
ai.jina.hub.kind="crafter" \      
ai.jina.hub.jina_version="0.9.18"
# setup the workspace
COPY . /workspace
WORKDIR /workspace

# install the third-party requirements
RUN pip install -r requirements.txt --no-cache-dir

# for testing the image
FROM base
LABEL ai.jina.hub.name="AlbumentationsCrafter" \      
ai.jina.hub.description="Apply transformations from the Albumentations package to the image." \      
ai.jina.hub.type="pod" \      
ai.jina.hub.author="Tadej Svetina (@tadejsv)" \      
ai.jina.hub.url="https://jina.ai" \      
ai.jina.hub.documentation="https://github.com/jina-ai/jina-hub" \      
ai.jina.hub.version="0.0.1" \      
ai.jina.hub.vendor="Jina AI Limited" \      
ai.jina.hub.license="apache-2.0" \      
ai.jina.hub.avatar="None" \      
ai.jina.hub.platform="['linux/amd64']" \      
ai.jina.hub.keywords="['image', 'transform', 'augmentation', 'albumentations']" \      
ai.jina.hub.manifest_version="1" \      
ai.jina.hub.kind="crafter" \      
ai.jina.hub.jina_version="0.9.18"RUN pip install pytest && pytest

FROM base
LABEL ai.jina.hub.name="AlbumentationsCrafter" \      
ai.jina.hub.description="Apply transformations from the Albumentations package to the image." \      
ai.jina.hub.type="pod" \      
ai.jina.hub.author="Tadej Svetina (@tadejsv)" \      
ai.jina.hub.url="https://jina.ai" \      
ai.jina.hub.documentation="https://github.com/jina-ai/jina-hub" \      
ai.jina.hub.version="0.0.1" \      
ai.jina.hub.vendor="Jina AI Limited" \      
ai.jina.hub.license="apache-2.0" \      
ai.jina.hub.avatar="None" \      
ai.jina.hub.platform="['linux/amd64']" \      
ai.jina.hub.keywords="['image', 'transform', 'augmentation', 'albumentations']" \      
ai.jina.hub.manifest_version="1" \      
ai.jina.hub.kind="crafter" \      
ai.jina.hub.jina_version="0.9.18"ENTRYPOINT ["jina", "pod", "--uses", "config.yml"]
```

2021-01-20 07:17 UTC, JoanFM commented
> @JoanFM also (probably) not the root of the problem, but when exploring the URL of the docker request, it seems that jina inserts labels after every `FROM` line in the dockerfile. The correct way would be to do it only after the last `FROM`
> 
> Here's the decoded URL:
> 
> ```
> docker://localhost/v1.40/build?t=jinahub/pod.crafter.albumentationscrafter:0.0.1-0.9.18&q=False&nocache=False&rm=True&forcerm=False&pull=True&dockerfile=.dockerfile.85ba69d05f9914e2aef3438da3fd8b99512ce32e&dockerfile=FROM jinaai/jina AS base
> LABEL ai.jina.hub.name="AlbumentationsCrafter" \      
> ai.jina.hub.description="Apply transformations from the Albumentations package to the image." \      
> ai.jina.hub.type="pod" \      
> ai.jina.hub.author="Tadej Svetina (@tadejsv)" \      
> ai.jina.hub.url="https://jina.ai" \      
> ai.jina.hub.documentation="https://github.com/jina-ai/jina-hub" \      
> ai.jina.hub.version="0.0.1" \      
> ai.jina.hub.vendor="Jina AI Limited" \      
> ai.jina.hub.license="apache-2.0" \      
> ai.jina.hub.avatar="None" \      
> ai.jina.hub.platform="['linux/amd64']" \      
> ai.jina.hub.keywords="['image', 'transform', 'augmentation', 'albumentations']" \      
> ai.jina.hub.manifest_version="1" \      
> ai.jina.hub.kind="crafter" \      
> ai.jina.hub.jina_version="0.9.18"
> # setup the workspace
> COPY . /workspace
> WORKDIR /workspace
> 
> # install the third-party requirements
> RUN pip install -r requirements.txt --no-cache-dir
> 
> # for testing the image
> FROM base
> LABEL ai.jina.hub.name="AlbumentationsCrafter" \      
> ai.jina.hub.description="Apply transformations from the Albumentations package to the image." \      
> ai.jina.hub.type="pod" \      
> ai.jina.hub.author="Tadej Svetina (@tadejsv)" \      
> ai.jina.hub.url="https://jina.ai" \      
> ai.jina.hub.documentation="https://github.com/jina-ai/jina-hub" \      
> ai.jina.hub.version="0.0.1" \      
> ai.jina.hub.vendor="Jina AI Limited" \      
> ai.jina.hub.license="apache-2.0" \      
> ai.jina.hub.avatar="None" \      
> ai.jina.hub.platform="['linux/amd64']" \      
> ai.jina.hub.keywords="['image', 'transform', 'augmentation', 'albumentations']" \      
> ai.jina.hub.manifest_version="1" \      
> ai.jina.hub.kind="crafter" \      
> ai.jina.hub.jina_version="0.9.18"RUN pip install pytest && pytest
> 
> FROM base
> LABEL ai.jina.hub.name="AlbumentationsCrafter" \      
> ai.jina.hub.description="Apply transformations from the Albumentations package to the image." \      
> ai.jina.hub.type="pod" \      
> ai.jina.hub.author="Tadej Svetina (@tadejsv)" \      
> ai.jina.hub.url="https://jina.ai" \      
> ai.jina.hub.documentation="https://github.com/jina-ai/jina-hub" \      
> ai.jina.hub.version="0.0.1" \      
> ai.jina.hub.vendor="Jina AI Limited" \      
> ai.jina.hub.license="apache-2.0" \      
> ai.jina.hub.avatar="None" \      
> ai.jina.hub.platform="['linux/amd64']" \      
> ai.jina.hub.keywords="['image', 'transform', 'augmentation', 'albumentations']" \      
> ai.jina.hub.manifest_version="1" \      
> ai.jina.hub.kind="crafter" \      
> ai.jina.hub.jina_version="0.9.18"ENTRYPOINT ["jina", "pod", "--uses", "config.yml"]
> ```

it could very much be the root of the problem, you can please add it as a hint when opening the issue

2021-01-20 07:20 UTC, tadejsv commented
Ok, found the actual problem: after labels jina does not insert (perserve) the linebreak. Will raise it as an issue

2021-01-20 07:24 UTC, tadejsv commented
The CI is now passing as I added line breaks after the `FROM` statement, which circumvents the issue.

2021-01-20 07:36 UTC, JoanFM approved these changes

2021-01-20 07:36 UTC, JoanFM commented
Hey @tadejsv ,

Thank you very much for yet another great contribution!

2021-01-20 07:36 UTC, merged