feat: update doc for vse encoder
jina-ai/jina-hub pull request #3669
Opened 2021-02-12 06:49 UTC by rutujasurve94

2021-02-15 13:31 UTC, JoanFM reviewed
You need to bump the version for it to be tested

2021-02-15 13:33 UTC, JoanFM requested changes

2021-02-15 13:33 UTC, JoanFM commented on encoders/image/VSEImageEncoder/README.md
> + Note:
Do not add it here, since is a common issue, let's avoid putting in every README

2021-02-15 13:33 UTC, JoanFM commented on encoders/image/VSEImageEncoder/README.md
> +    jina pod --uses hub/example/vseimageencoder.yml --port-in 55555 --port-out 55556
you should use `config.yml` then

2021-02-15 13:33 UTC, JoanFM commented on encoders/image/VSEImageEncoder/README.md
> +        .add(name='my-indexer', uses='indexer.yml'))
there is no need to add indexer or anything else, this executor is only about the encoder

2021-02-15 13:33 UTC, JoanFM commented on encoders/image/VSEImageEncoder/README.md
> +    jina pod --uses hub/example/vseimageencoder.yml --port-in 55555 --port-out 55556
It is more important to see how the parameters are passed in a `yaml` configuration

2021-02-22 09:07 UTC, rutujasurve94 commented
Closing this since https://github.com/jina-ai/jina-hub/pull/3878/files already solves the documentation issue for VSE encoder

2021-02-22 09:07 UTC, closed without merging