fix: scann indexer
jina-ai/jina-hub pull request #3675
Opened 2021-02-12 15:55 UTC by florian-hoenicke

2021-02-12 16:02 UTC, JoanFM requested changes

2021-02-12 16:02 UTC, JoanFM commented on indexers/vector/ScannIndexer/tests/test_scannindexer.py
> +        indexer.add([str(e) for e in vec_idx], vec)
change the type of vecidx

2021-02-12 16:18 UTC, JoanFM reviewed
vec_idx = np.random.randint(0, high=100, size=[10])

This should be casted to `astype(str)`

2021-02-12 16:31 UTC, florian-hoenicke commented on indexers/vector/ScannIndexer/tests/test_scannindexer.py
> +        indexer.add([str(e) for e in vec_idx], vec)
true, I made it more readable. Thanks

2021-02-13 18:39 UTC, JoanFM approved these changes

2021-02-13 18:43 UTC, merged