docs(sentencizer): update readme and manifest
jina-ai/jina-hub pull request #3863
Opened 2021-02-16 22:33 UTC by Yongxuanzhang

This pr is for JINAHUBV1-370.

2021-02-17 08:14 UTC, FionnD commented
I'm adding @lusloher as a reviewer instead of me since this is her area :)

2021-02-17 10:04 UTC, theUnkownName submitted a review, later dismissed

2021-02-17 11:55 UTC, theUnkownName commented on segmenters/nlp/Sentencizer/manifest.yml
>  keywords: [text, nlp, segement]
typo in Segment

2021-02-17 12:36 UTC, cristianmtr commented on segmenters/nlp/Sentencizer/README.md
> +Sentencizer is one segmenter used in nlp domain. It splits the text on the doc-level into sentences on the chunk-level with a rule-base strategy.
```suggestion
Sentencizer is one segmenter used in the NLP domain. It splits the text on the doc-level into sentences on the chunk-level with a rule-base strategy.
```

2021-02-17 12:36 UTC, cristianmtr commented on segmenters/nlp/Sentencizer/README.md
> +##Usage:
Line break. Rendering broken

2021-02-17 12:37 UTC, cristianmtr requested changes
small thing

2021-02-17 14:47 UTC, lusloher approved these changes
Looks good from my side

2021-02-17 15:10 UTC, FionnD submitted a review, later dismissed

2021-02-17 16:09 UTC, Yongxuanzhang commented on segmenters/nlp/Sentencizer/manifest.yml
>  keywords: [text, nlp, segement]
✅

2021-02-17 16:09 UTC, Yongxuanzhang commented on segmenters/nlp/Sentencizer/README.md
> +Sentencizer is one segmenter used in nlp domain. It splits the text on the doc-level into sentences on the chunk-level with a rule-base strategy.
✅

2021-02-17 16:09 UTC, Yongxuanzhang commented on segmenters/nlp/Sentencizer/README.md
> +##Usage:
✅

2021-02-18 14:25 UTC, cristianmtr approved these changes

2021-02-18 14:57 UTC, merged