fix: add jina hub new type
jina-ai/jina-hub pull request #404
Opened 2020-09-07 12:14 UTC by rutujasurve94

Updating README for new `--type` argument for `jina hub new`

2020-09-07 12:28 UTC, hanxiao commented on README.md
> +jina hub new --type='pod'
```suggestion
jina hub new --type pod
```

2020-09-07 12:28 UTC, hanxiao commented on README.md
> +2. `pip install jina[hub] && jina hub new --type='pod'`
```suggestion
2. `pip install jina[hub] && jina hub new --type pod`
```

2020-09-07 12:28 UTC, hanxiao requested changes
single-quote is unnecessary

2020-09-08 05:58 UTC, rutujasurve94 commented on README.md
> +jina hub new --type='pod'
Done

2020-09-08 05:59 UTC, rutujasurve94 commented on README.md
> +2. `pip install jina[hub] && jina hub new --type='pod'`
Done

2020-09-08 10:53 UTC, merged