feat: add docs for keras image encoder
jina-ai/jina-hub pull request #4236
Opened 2021-02-22 09:01 UTC by rutujasurve94

Doc for `kerasimage` encoder

2021-02-22 09:06 UTC, JoanFM requested changes

2021-02-22 09:06 UTC, JoanFM commented on encoders/image/ImageKerasEncoder/README.md
> +`ImageKerasEncoder` encodes data from a ndarray, potentially B x (Channel x Height x Width) into a ndarray of `B x D`. Internally, :class:`ImageKerasEncoder` wraps the models from `tensorflow.keras.a
Can u say what the `B` stands for

2021-02-22 09:06 UTC, JoanFM commented on encoders/image/ImageKerasEncoder/README.md
> +| `model_name`  | includes `MobileNetV2`  |
what other possibilities?

2021-02-22 09:06 UTC, JoanFM commented on encoders/image/ImageKerasEncoder/README.md
> +| `channel_axis`| axis id of the channel, etc.  |
axis of the `color` channel

2021-02-22 09:06 UTC, JoanFM commented on encoders/image/ImageKerasEncoder/README.md
> +| `pool_strategy` | strategy like `avg` |
strategy for the pooling operation

2021-02-23 11:41 UTC, rutujasurve94 commented on encoders/image/ImageKerasEncoder/README.md
> +| `model_name`  | includes `MobileNetV2`  |
added other possibilities

2021-02-23 11:42 UTC, JoanFM approved these changes

2021-02-23 12:30 UTC, merged