Doc custom keras image encoder
jina-ai/jina-hub pull request #4601
Opened 2021-02-26 13:42 UTC by davidbp

2021-02-28 15:42 UTC, bwanglzu submitted a review, later dismissed
LGTM!

2021-03-01 09:59 UTC, JoanFM requested changes

2021-03-01 09:59 UTC, JoanFM commented on encoders/image/CustomKerasImageEncoder/README.md
> +##
should these be removed?

2021-03-01 10:20 UTC, davidbp commented on encoders/image/CustomKerasImageEncoder/README.md
> +##
yes, they are removed now

2021-03-01 10:21 UTC, JoanFM approved these changes

2021-03-02 03:03 UTC, merged