feat(classifier): implement transformer torch sequence classifier
jina-ai/jina-hub pull request #6749
Opened 2021-03-22 18:08 UTC by mezig351

https://github.com/jina-ai/jina-hub/issues/6191 implemented.

2021-03-23 06:09 UTC, nan-wang requested changes

2021-03-23 06:09 UTC, nan-wang commented on classifiers/nlp/TransformersTorchSeqClassifier/tests/test_transformerstorchseqclassifier.py
> +    print(output.argmax(axis=1))
```suggestion
```

2021-03-23 06:09 UTC, nan-wang commented on classifiers/nlp/TransformersTorchSeqClassifier/tests/test_transformerstorchseqclassifier.py
> +    assert output.shape[0] == 3
Try to make the test easier to understand
```suggestion
    assert output.shape[0] == data.shape[0]
```

2021-03-23 06:10 UTC, nan-wang commented
Good job! Many thanks for your contribution.

2021-03-23 06:10 UTC, nan-wang commented
recheckcla

2021-03-24 02:42 UTC, nan-wang approved these changes
LGTM👍

2021-03-24 02:42 UTC, merged

2021-03-24 02:42 UTC, nan-wang commented
**Jina CLA check**<br/>
  ❤️ Thank you for your pull request. It looks like this is your first contribution to an open source project maintained by Jina AI Limited. Before we can look at your pull request, we kindly ask that you sign our [Contributor License Agreement](https://github.com/jina-ai/jina/blob/master/.github/CLA.md). You can sign it by commenting in format below.
  - - -
  ***I have read the CLA Document and I hereby sign the CLA***
  - - -

2021-03-24 02:42 UTC, nan-wang commented
hi, there. @mezig351  Thanks for the PR. Your contribution is greatly appreciated. Would you please sign the CLA above so that we can proceed to merge this PR?

2021-03-24 06:54 UTC, mezig351 commented
I have read the CLA Document and I hereby sign the CLA