feat: added 2 0 indexers
jina-ai/jina-hub pull request #8176
Opened 2021-05-06 08:37 UTC by maximilianwerk

Showcasing 2.0 indexers, including trivial(!) compounding.

2021-05-06 11:58 UTC, cristianmtr requested changes

2021-05-06 11:58 UTC, cristianmtr commented on indexers/dbms/BinaryPbIndexer/binarypb.py
> +__copyright__ = "Copyright (c) 2020 Jina AI Limited. All rights reserved."
not sure what happened here

2021-05-06 11:58 UTC, cristianmtr commented on indexers/dbms/BinaryPbIndexer/__init__.py
> +        Check if the database is exist or not
phrasing is off. I know it was there before, but now it's the time to change it :)

```suggestion
        Check if the database exists or not
```

2021-05-06 11:58 UTC, cristianmtr commented on indexers/dbms/BinaryPbIndexer/__init__.py
> +        """A writable and indexable object, could be dict, map, list, numpy array etc.
docstring does not reflect implementation

2021-05-06 11:58 UTC, cristianmtr commented on indexers/dbms/BinaryPbIndexer/__init__.py
> +        The number of vectors or documents indexed.
```suggestion
        The number of documents indexed.
```

2021-05-06 11:58 UTC, cristianmtr commented on indexers/dbms/BinaryPbIndexer/__init__.py
> +    def default_dump_path(self):
Maybe a docstring

2021-05-06 11:58 UTC, cristianmtr commented on indexers/dbms/BinaryPbIndexer/binarypb.py
> +                # self.header = {
remove

2021-05-06 11:58 UTC, cristianmtr commented on indexers/dbms/BinaryPbIndexer/query_compound.py
> +        kv_parameters['traversal_paths'] = [
so does this work?

2021-05-07 06:15 UTC, maximilianwerk commented on indexers/dbms/BinaryPbIndexer/query_compound.py
> +        kv_parameters['traversal_paths'] = [
Yes :D

2021-05-18 15:11 UTC, merged

2021-05-19 03:35 UTC, Kelton8Z commented
I wonder if this can be merged into master ?

2021-05-19 06:23 UTC, maximilianwerk commented
> I wonder if this can be merged into master ?

No, because jina-hub has not yet changed to the 2.0 pattern.