feat: add lightgbm ranker trainer
jina-ai/jina-hub pull request #8268
Opened 2021-05-10 12:46 UTC by bwanglzu

2021-05-12 07:24 UTC, JoanFM requested changes

2021-05-12 07:24 UTC, JoanFM commented on ranker_trainer/LightGBMRankerTrainer/__init__.py
> +        self.model = lgb.train(
we need warm start, incremental training. This is training a new model each time right.

2021-05-17 10:31 UTC, JoanFM requested changes

2021-05-17 10:31 UTC, JoanFM commented on ranker_trainer/LightGBMRankerTrainer/__init__.py
> +            raise FileNotFoundError(f'The model path {self.model_path} not found.')
If the model path does not exist, maybe is because u want to train from scratch, put a message to warn and ad `self.model = None`

2021-05-17 10:31 UTC, JoanFM commented on ranker_trainer/LightGBMRankerTrainer/__init__.py
> +            init_model=self.model_path,
`init_model` should be `self.model` so that it is updated at every iteration.

2021-05-17 13:02 UTC, JoanFM requested changes

2021-05-17 13:02 UTC, JoanFM commented on ranker_trainer/LightGBMRankerTrainer/tests/test_lightgbm_ranker_trainer.py
> +    return {'num_leaves': 31, 'objective': 'binary'}
it is better to prove with `ndcg` loss

2021-05-17 13:02 UTC, JoanFM commented on ranker_trainer/LightGBMRankerTrainer/requirements.txt
> +jina>=1.2.3
this is not needed, since the docker already has jina

2021-05-17 13:02 UTC, JoanFM commented on ranker_trainer/LightGBMRankerTrainer/__init__.py
> +    def is_trained(self):
is this needed?

2021-05-17 13:48 UTC, bwanglzu commented on ranker_trainer/LightGBMRankerTrainer/__init__.py
> +    def is_trained(self):
it's used in `save` and test

2021-05-17 14:54 UTC, JoanFM commented on ranker_trainer/LightGBMRankerTrainer/tests/test_lightgbm_ranker_trainer.py
> +    return np.array([-0.9898187, -0.8011962])
isnt this a little fragile? Arr we sure it is deterministic?

2021-05-19 14:32 UTC, JoanFM commented on ranker_trainer/LightGBMRankerTrainer/__init__.py
> +            labels = np.array([item[self.label_feature_name] for item in m_meta])
why do we need an `np.array`? isn't a list enough?

2021-05-20 05:42 UTC, nan-wang requested changes
LGTM👍 I suggest putting this under the `/trainers` folder. Plus, remember to update the `ci.yml` so that the test is included during CI.

https://github.com/jina-ai/jina-hub/blob/master/.github/workflows/ci.yml#L29

2021-05-20 12:19 UTC, JoanFM requested changes

2021-05-20 12:19 UTC, JoanFM commented on trainers/LightGBMRankerTrainer/__init__.py
> +        else:
we do not need this. If it does not exist, we will train from scratch

2021-05-20 12:19 UTC, JoanFM commented on trainers/LightGBMRankerTrainer/__init__.py
> +        else:
in this else branch u can assign.

`self.model = lgb.Booster()`

2021-05-20 15:08 UTC, JoanFM commented on trainers/LightGBMRankerTrainer/README.md
>  This ranker trainer allows the offline training of any learning-to-rank model trained using [LightGBM](https://lightgbm.readthedocs.io/en/latest/index.html) to rank a list of search results.
I would not say offline. I would also mention incremental learning

2021-05-20 23:23 UTC, nan-wang approved these changes
LGTM👍

2021-05-25 13:41 UTC, JoanFM approved these changes

2021-05-25 13:41 UTC, merged